SECRET_KEY ='random_key'
SQLALCHEMY_DATABASE_URI='sqlite:///database.db'
MAIL_SERVER='smtp-mail.outlook.com'
MAIL_PORT=587
MAIL_USERNAME='BUssin.supp0rt@outlook.com'
MAIL_PASSWORD='chaewonfan69'
MAIL_USE_TLS=True
MAIL_USE_SSL=False
MAIL_DEFAULT_SENDER='BUssin.supp0rt@outlook.com'